- libexec/apple-llvm/helpers/mt_db.sh
- test/mt/generate/self-heal-reuse-mtrepo-but-forget-to-remove-mtdb-worktree.test
If there's no refs/mt/mt-db and we're creating a new one delete any
existing mt-db worktree.  Having this would have saved me a lot of
annoying delays recently, when I've been reusing an existing
`mt-repo.git` and testing an mt-generate change.
> mt-generate: Automatically clean up mt-db worktree if there is no ref

- src/commit_interleaver.h
- src/git_cache.h
8bf1494af87f is a split commit in github.com/apple/swift-clang that is a
strange style of cherry-pick of r354826.  The strange bit is that the
committer and author metadata match exactly.  This is not supposed to be
possible, since when using `git-cherry-pick` a collision should only
occur when the following all happen in the same second:
- Push to SVN.
- Wait for `git-svn` mirrors to update.
- Fetch.
- Cherry-pick to a branch.
This being vanishingly unlikely, I had assumed only a malicious actor
would add such a commit, and based the heuristics for "is this a
cherry-pick or a real llvm.org commit?" on seeing a mismatch.
Unfortunately there's at least one exception, the above cherry-pick.
Somehow, the committer and author metadata match each other exactly.
The cherry-picker must have done …
> split2mono: Prevent 8bf1494af87f from being identified as r354826

- docs/ContributingToTools.md
- src/Programs.mk
- src/commit_interleaver.h
- src/git_cache.h
- src/split2mono.cpp
- test/bin/mkblob-svn
- test/bin/test/mkblob-svn.test
- test/split2mono/svn-fast-cherry-pick-and-merge-reverse.test
- test/split2mono/svn-fast-cherry-pick-and-merge.test
- test/split2mono/svn-fast-cherry-pick.test
- test/split2mono/svn-merge-mismatched-date.test
- test/split2mono/svn-merge-mismatched-email.test
- test/split2mono/svn-merge-mismatched-name.test
- test/split2mono/svn-merge-not-in-monorepo.test
- test/split2mono/svn-merge.test
split2mono: Strengthen heuristic for detecting upstream git-svn commits
Improve the heuristic for detecting upstream git-svn commits.  Now we
only parse the commit metadata looking for `git-svn-id:` when (a) the
commit is not a merge, (b) the parent commit (if any) has not been
generated by split2mono, and (c) the author and committer info match
exactly.  Before this commit, the only check was (c).
This required some (perhaps overdue) refactoring of compute_rev to make
the logic for split commits and monorepo commits clear (and, in some
cases, different).  A few functions in `git_cache` were renamed for
clarity.
The tests use an invented history that looks like an LLVM subproject,
with `git-svn-id:` for the split commits and `llvm-rev:` for the
monorepo commits.
> split2mono: Strengthen heuristic for detecting upstream git-svn commits

- libexec/apple-llvm/git-apple-llvm-mt-generate
Stop using `git --file path/to/config` since some of our bots don't
support it.  Use `git -C path/to/clone --local` instead.
> mt-generate: Don't use `git --file`

- libexec/apple-llvm/git-apple-llvm-mt-generate
6569ecd0405defd3bb4e24537485d91ea9f2880a did not help; the real problem
was passing arguments to `git` instead of `git-config`.  Fix that.
Pull request is just so I can run tests; no need to actually review.
> mt-generate: Use `git config --file`

- libexec/apple-llvm/git-apple-llvm-mt-translate-branch
Avoid initializing the mt-db checkout when checking for work.  This
should speed up syncing destinations in mt-generate a little.
> mt-translate-branch: Optimize --check-for-work

- mt-config/apple-v2.mt-config
The history in apple-v1 is corrupted, since a number of cherry-pick
commits were mis-identified as the original upstream commits.  Add a
configuration for apple-v2 so we can build a fresh history now that the
bugs in `split2mono` have been fixed.
> mt-config: Add apple-v2, to generate a fresh history

- src/commit_interleaver.h
- src/git_cache.h
- test/mt-generate/Inputs/repeat-two-dirs.mt-config.in
- test/mt-generate/Inputs/root-merge-heads.mt-config.in
- test/mt-generate/repeat-root-2.test
- test/mt-generate/repeat-root.test
- test/mt-generate/repeat-two-dirs.test
- test/mt-generate/root-merge-heads.test
- test/split2mono/repeat.test
Two bug fixes and two cosmetic changes for generated `repeat` merges.
- Fix content for generated merges of root directory commits.
- Fix octopus merges of heads involving the root directory.
- Prune the list of directories in generated repeat merges to just those that have changes.
- Change the generated merge email to `mt@apple-llvm`, dropping spaces.
> split2mono: Fix a few problems with repeat directives

- mt-config/apple-v4.mt-config
This is identical to apple-v3.mt-config.  It should not be merged until we have the fixes from here:
https://github.com/apple/apple-llvm-infrastructure-tools/pull/47
> mt-config: Add apple-v4.mt-config

- libexec/apple-llvm/git-apple-llvm-mt-generate
It seems like running the tool from a fresh clone will not always fetch
the tags right now.  Try harder.
> mt-generate: Fetch tags from the monorepo destination

- libexec/apple-llvm/git-apple-llvm-mt-generate
- src/commit_interleaver.h
- src/commit_source.h
- src/dir_list.h
- test/mt-generate/Inputs/repeat-two-dirs.mt-config.in
- test/mt-generate/repeat-two-dirs.test
`mt-translate-ref` is sometimes (but rarely) called when there are new
commits on the branch getting repeated, but none of them affect the
"repeated" dirs.  Ensure that we don't generate merge commits for those,
since it makes the history extra confusing (even without this change,
the content was correct).
As a drive-by, avoid comparing trees twice.
> mt-generate: Ensure that `repeat` is a no-op when it should be

- mt-config/apple-v5.mt-config
We're regenerating (again) after a bugfix in `split2mono`.
The main change is to repeat `dir`s in favour of `repeat`s.
The `split2mono` tool supports "auto" repeats of `dir`s that are shared
between branches.  When we can use that it's more precise than a
`repeat`, because it will follow `--ancestry-path` instead of relying on
`--first-parent` (which could fail to generate a good history).  Prefer
that where possible.
Also fixed two things as drive-bys:
- Filled in the start directive for swift/master/start, which had been
half typed in before.
- Fixed spelling for the clang-tools-extra `dir` on
apple/master/root-start.
> apple-v5: Prepare for another regeneration

- libexec/apple-llvm/git-apple-llvm-mt-generate
- test/mt-generate/Inputs/alias-branch.mt-config.in
- test/mt-generate/alias-branch.test
Before the big `split2mono` rewrite over the last couple of weeks, if no
new commits were translated that meant we wouldn't create a ref.  Now we
do, and we need to push it.
> mt-generate: Push new refs even if they are aliases

- libexec/apple-llvm/git-apple-llvm-mt-generate
Adjust to the monorepo having transitioned upstream at llvm.org, by
looking backward for the most recent commit with `llvm-svn:`.
> mt-generate: Fix mapping for post-monorepo transition on llvm.org

- Makefile
This removes the PIP configuration variable and folds it into the
prefix selection, ie:
- If someone specifies a directory that exists as a prefix, use the
pip that's inside it.
- If the prefix is a directory that doesn't exist, create a virtualenv
there first.
> Use a python virtualenv if installing with a PREFIX

- git_apple_llvm/git_tools/push.py
Early on, we changed from `llvm/` to `llvm.org/` as a prefix for refs
forwarded from `github.com/llvm/llvm-project`.  Looks like
`git apple-llvm push` wasn't updated.
> push: Fix branch name for llvm.org branches

- libexec/apple-llvm/git-apple-llvm-fwd
- test/fwd/master.test
This was setting GIT_DIR, but since it wasn't exported the git
commands would just create a git repo in the current directory
instead.
> Make sure to export GIT_DIR in git-apple-llvm-fwd

- git_apple_llvm/git_tools/__init__.py
- git_apple_llvm/git_tools/push.py
This is necessary to use get_dev_null from other places when using the
git function.
> [git_tools] Make get_dev_null available from git_tools.

- git_apple_llvm/am/am_graph.py
This improves the graph layout for complex configurations by disabling
the constraint attribute on the secondary edge so that it's not used in
ranking the edges.
> [am] Improve graph layout by unconstraining secondary edge

- git_apple_llvm/am/core.py
This normalizes the dates and makes it more comprehensible.
> Show commit dates in the local timezone

- test/requirements.txt
We have requirement for GitPython==2.1.11 which in turn requires GitDB.
There’s been a new version of GitDB and it has removed
`gitdb.utils.compat`. Since we pin GitPython to an older version, we’ll
have to pin GitDB to a corresponding working version too. Choosing 3.0.1
as that appears to be the last known working version.
> Pin gitdb2 to version 2.0.6

- test/Makefile
- test/am/test_am_config.py
- test/am/test_am_status.py
- test/am/test_merge_conflict.py
- test/am/test_secondary_edge_status.py
- test/git-tools/test_push.py
- test/pr/test_pr_tool.py
- test/requirements.txt
The order is:
- check-types
- check-lint
- check-pytest (and/or any pytest targets)
- check-lit (and/or any lit targets)
This creates the check-pytest target which runs all pytests at once and
changes check-all to use it.
Three commits here:
- First commit gets most existing tests passing, fixing a problem with Click.
- Second commit does the main work, but loses parallelism between pytest invocations.
- Third commit brings back parallelism using pytest-xdist.
> test: Order check-* to avoid interleaving output

- libexec/apple-llvm/git-apple-llvm-fwd
- test/fwd/master.test
`protocol.version=2` requires Git v2.18.0+.  Temporarily revert a couple of patches until the bot is upgraded.
> Revert protocol.version=2-reliant patches (temporarily)

- libexec/apple-llvm/git-apple-llvm-fwd
- test/fwd/protocol.test
- test/lit.cfg
This reverts commit c742c71eb5d67b717d3524ae790043086026de19, reapplying
68252361ac8739115abd943a99695bec75ef76f4 with a check against the Git
verison.
Radar-Id: rdar://problem/61639016
> Reapply "fwd: Use protocol.version=2"

- libexec/apple-llvm/git-apple-llvm-fwd
This reverts commit 9dc4129cc3c34005e2a1bb9320e52529b0616f43, reaplying
68252361ac8739115abd943a99695bec75ef76f4 with a check against the Git
version.
Radar-Id: rdar://problem/61639392
> Reapply "fwd: Leverage --negotation-tip to optimize fetch"

- libexec/apple-llvm/git-apple-llvm-fwd
We're (ab)using `git-push` to use the refspecs directly for simulating
the actual push, but it's really confusing for anyone looking at the
logs (and for large amounts of refs, it's super harmful for reading
them).  Suppress the output with `--quiet` when pushing to `GIT_DIR`.
Radar-Id: rdar://problem/61650270
> fwd: Be quiet when moving refs en masse locally

- libexec/apple-llvm/git-apple-llvm-fwd
I had the minimum version wrong for using `--negotition-tip` and got
confused by server logs.
- Bump it to v2.19;
- use globs directly, since that should work from the start; and
- simplify the version checking function.
Radar-Id: rdar://problem/61651587
> fwd: Update --negotiation-tip min version to Git v2.19

- git_apple_llvm/am/am_status.py
- test/am/test_am_config.py
- test/am/test_secondary_edge_status.py
Always show how many commits are waiting in zippered merge branches,
even when the automerger is unblocked.
As a drive-by, simplify some of the prose.
> am-status: Always show number of unmerged commits in zippered merges

- make-helpers/python_venv_requirements.mk
This reverts commit 9bc189ea83cab1e74d78d2f97e4b123ee0a8e13d.
It is failing to compile the cffi module.
c/_cffi_backend.c:5854:2: error: Apple Arm64 ABI requires ffi_prep_cif_var
#error Apple Arm64 ABI requires ffi_prep_cif_var
^
1 error generated.
error: command 'xcrun' failed with exit status 1
> Revert "Use xcrun python3 for make test/docs if available"

- git_apple_llvm/am/am_status.py
Remove the "Conflict" state based on a local merge attempt (as opposed
tot he "CONFLICT" state based on the CI) as the former doesn't take into
account resolutions pushed to the AM.
rdar://60848531
> Automerger status check should not check for local merge conflict.
