apple/apple-llvm-infrastructure-tools

- apple-llvm-config/pr.json
- git_apple_llvm/pr/github_pr_tool.py
- git_apple_llvm/pr/main.py
- git_apple_llvm/pr/pr_tool.py
- setup.py
- test/Makefile
- test/pr/github_mock_pr_tool.py
- test/pr/mock_pr_tool.py
- test/pr/test_pr_tool.py
Recreated #12 to avoid GitHub glitches.
> Initial implementation of the "git apple-llvm pr" tool with "list" and "test" support 

- git_apple_llvm/am/main.py
- git_apple_llvm/am/oracle.py
- setup.py
> [automerger] Add support for the redis merge state commands

- git_apple_llvm/am/am_graph.py
- git_apple_llvm/am/main.py
This adds the 'graph' sub-command to the am tool to generate and display
the automerger graph using graphviz.
> [am] Add 'graph' tool that prints the automerger graph using graphviz.

- git_apple_llvm/am/am_status.py
- git_apple_llvm/am/core.py
Move this functionality into core so it can be reused from the graph utility.
> [am] Move find_inflight_merges into am.core (NFC)

- git_apple_llvm/am/am_graph.py
- git_apple_llvm/am/main.py
This changes the color of the edges to green or red based on the status
of the automerger. I've also made the nodes gray as the light blue
didn't work very well with the colored edges.
> [am] Color edges based on AM status

- .gitignore
This ignores files created while running the test suite.
> [gitignore] Ignore distribution and mypy files

- git_apple_llvm/am/am_graph.py
The nodes in the automerger graph correspond to branches in different
repositories. This patch uses the branch name to determine the
repository (llvm, github, internal) and adds the nodes to distinct
subgraphs. This visualizes the relationship between the branches and
highlights cross-repository merges.
> [am] Split automerger graph into subgraphs.

- git_apple_llvm/am/am_status.py
- test/am/test_secondary_edge_status.py
> [am] Fix typo for the zippered merge branch

- git_apple_llvm/am/am_graph.py
- git_apple_llvm/am/am_status.py
- git_apple_llvm/am/core.py
- test/am/test_merge_conflict.py
Remove the method is_secondary_edge_commit_blocked_by_primary_edge and
replace the functionality with trying to do the merge locally.
> [am] Remove is_secondary_edge_commit_blocked_by_primary_edge

- test/mt-generate/repeat-root-2.test
This is failing during PR testing.
rdar://problem/57991261
> [test] Temporarily disable repeat-root-2.test

- git_apple_llvm/am/am_graph.py
Combine edge properties into a new Edge class.
> [am] Create Edge abstraction

- test/mt-generate/repeat-root-2.test
The race condition should have been fixed.
> Revert "[test] Temporarily disable repeat-root-2.test"

- libexec/apple-llvm/git-apple-llvm-fwd
Radar-Id: rdar://problem/61637856
> fwd: Use --prune when fetching

- libexec/apple-llvm/git-apple-llvm-fwd
Radar-Id: rdar://problem/61638808
> fwd: Use --bare repo

- libexec/apple-llvm/git-apple-llvm-fwd
Radar-Id: rdar://problem/61638475
> fwd: Skip fetch for push-only remotes

- libexec/apple-llvm/git-apple-llvm-fwd
- test/fwd/master.test
Radar-Id: rdar://problem/61639016
> fwd: Use protocol.version=2

- libexec/apple-llvm/git-apple-llvm-fwd
Avoid negotating with large numbers of refs, for the most part we
are just mirroring the remote here.
Radar-Id: rdar://problem/61639392
> fwd: Leverage --negotation-tip to optimize fetch

- libexec/apple-llvm/git-apple-llvm-fwd
Radar-Id: rdar://problem/61639802
> fwd: Push once per destination

- libexec/apple-llvm/git-apple-llvm-fwd
- test/fwd/force.test
- test/fwd/master.test
Radar-Id: rdar://problem/61644213
> fwd: Support force-pushing refspecs

- docs/git-apple-llvm-fwd.md
- libexec/apple-llvm/git-apple-llvm-fwd
- test/fwd/master.test
Use a custom namespace of `refs/remote-tags/<remote>/*` to avoid collisions
between remotes.
Radar-Id: rdar://problem/61645747
> fwd: Add support for tags

- libexec/apple-llvm/git-apple-llvm-fwd
- test/fwd/master.test
Avoid pushing to the destination remote except when there is content
to forward.
Radar-Id: rdar://problem/61640121
> fwd: Only push if things have changed

- git_apple_llvm/am/graph.py
We have a new automerger edge for a new experimental branch.
> Update the known branch check
